version: '3'
  
services:
    nginx:
        image: httpd:2.4.46-alpine
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.project1.rule=Host(`project1.local`)"
            - "traefik.http.routers.project1.entrypoint=web"
        networks:
            - traefik
networks:
    traefik:
        external:
            name: traefik_proxy